name: tiny_types
description: >-
  Lightweight, focused utility types for Dart, including Option, Unit,
  non-empty collections, and practical utilities built around them.
version: 1.0.0
repository: https://github.com/hoc081098/tiny_types

environment:
  sdk: ^3.0.0

dependencies:
  meta: ^1.7.0

dev_dependencies:
  built_collection: ^5.1.1
  collection: ^1.17.0
  lints: ^3.0.0
  test: ^1.25.5
